dist: focal
language: python

python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install black mypy

script:
  - black --target-version py37 --check *.py
  - mypy --ignore-missing-imports *.py
  - python ./tests.py
