#!/usr/bin/env bash

EXECUTABLES_PATH="$HOME/code/computer-manager/executables"
mkdir -p "$EXECUTABLES_PATH"

git config --global user.email "bernardo@bernardosulzbach.com"
git config --global user.name "Bernardo Sulzbach"

git config --global push.default current

# Get Delta, a syntax-highlighter for git and diff output
wget "https://github.com/dandavison/delta/releases/download/0.1.1/delta-0.1.1-x86_64-unknown-linux-musl.tar.gz"
tar --extract --file "delta-0.1.1-x86_64-unknown-linux-musl.tar.gz"
mv "delta-0.1.1-x86_64-unknown-linux-musl/delta" "$EXECUTABLES_PATH/delta"
rm -rf "delta-0.1.1-x86_64-unknown-linux-musl"
rm -rf "delta-0.1.1-x86_64-unknown-linux-musl.tar.gz"
chmod +x "$EXECUTABLES_PATH/delta"

git config --global core.pager "$EXECUTABLES_PATH/delta --plus-color=\"#012800\" --minus-color=\"#340001\""
git config --global interactive.diffFilter "$EXECUTABLES_PATH/delta --color-only"

git config --global alias.co checkout
git config --global alias.history "log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --decorate --date=short"

git config --global commit.gpgsign true

# Better Git colors
git config --global color.ui true

git config --global color.diff-highlight.oldNormal "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"
git config --global color.diff.meta "yellow"
git config --global color.diff.frag "magenta bold"
git config --global color.diff.commit "yellow bold"
git config --global color.diff.old "red bold"
git config --global color.diff.new "green bold"
git config --global color.diff.whitespace "red reverse"

# Show UTF-8 as text, not escaped octal.
git config --global core.quotepath off
