#!/usr/bin/env bash

EXECUTABLES_PATH="$HOME/code/computer-manager/executables"
mkdir -p "$EXECUTABLES_PATH"

git config --global user.email "bernardo@bernardosulzbach.com"
git config --global user.name "Bernardo Sulzbach"

git config --global push.default current

# Set up Delta, a syntax-highlighter for git and diff output
git config --global core.pager "delta"
git config --global interactive.diffFilter "delta --color-only"
git config --global delta.light false
git config --global delta.navigate true

git config --global diff.colorMoved "default"

git config --global merge.conflictstyle "diff3"
git config --global merge.ff only

git config --global alias.br branch
git config --global alias.co checkout
git config --global alias.cp cherry-pick
git config --global alias.lsbr "for-each-ref --sort=-committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'"
git config --global alias.history "log --pretty=format:'%h %ad | %s%d [%an]' --graph --decorate --date=short"

git config --global commit.gpgsign true

# Better Git colors
git config --global color.ui true

git config --global color.diff-highlight.oldNormal "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"
git config --global color.diff.meta "yellow"
git config --global color.diff.frag "magenta bold"
git config --global color.diff.commit "yellow bold"
git config --global color.diff.old "red bold"
git config --global color.diff.new "green bold"
git config --global color.diff.whitespace "red reverse"

# Show UTF-8 as text, not escaped octal.
git config --global core.quotepath off
